# Generated by Django 2.1.3 on 2020-05-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super_user',
        ),
    ]
